
package gov.ga.legis.legislation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidSearchConstraintsFault", targetNamespace = "http://www.legis.ga.gov/2009/01/01/data/")
public class LegislationSearchGetLegislationSearchResultsPagedInvalidSearchConstraintsFaultFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidSearchConstraintsFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public LegislationSearchGetLegislationSearchResultsPagedInvalidSearchConstraintsFaultFaultFaultMessage(String message, InvalidSearchConstraintsFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public LegislationSearchGetLegislationSearchResultsPagedInvalidSearchConstraintsFaultFaultFaultMessage(String message, InvalidSearchConstraintsFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: gov.ga.legis.legislation.InvalidSearchConstraintsFault
     */
    public InvalidSearchConstraintsFault getFaultInfo() {
        return faultInfo;
    }

}
