
package gov.ga.legis.legislation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LegislationSearch", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LegislationSearch {


    /**
     * 
     * @param startIndex
     * @param pageSize
     * @param constraints
     * @return
     *     returns gov.ga.legis.legislation.LegislationSearchResultsPaged
     * @throws LegislationSearchGetLegislationSearchResultsPagedInvalidPageSizeFaultFaultFaultMessage
     * @throws LegislationSearchGetLegislationSearchResultsPagedInvalidSearchConstraintsFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetLegislationSearchResultsPaged", action = "http://www.legis.ga.gov/2009/01/01/services/LegislationSearch/GetLegislationSearchResultsPaged")
    @WebResult(name = "GetLegislationSearchResultsPagedResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetLegislationSearchResultsPaged", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetLegislationSearchResultsPaged")
    @ResponseWrapper(localName = "GetLegislationSearchResultsPagedResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetLegislationSearchResultsPagedResponse")
    public LegislationSearchResultsPaged getLegislationSearchResultsPaged(
        @WebParam(name = "Constraints", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        LegislationSearchConstraints constraints,
        @WebParam(name = "PageSize", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer pageSize,
        @WebParam(name = "StartIndex", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer startIndex)
        throws LegislationSearchGetLegislationSearchResultsPagedInvalidPageSizeFaultFaultFaultMessage, LegislationSearchGetLegislationSearchResultsPagedInvalidSearchConstraintsFaultFaultFaultMessage
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns gov.ga.legis.legislation.ArrayOfLegislationIndex
     */
    @WebMethod(operationName = "GetLegislationForSession", action = "http://www.legis.ga.gov/2009/01/01/services/LegislationSearch/GetLegislationForSession")
    @WebResult(name = "GetLegislationForSessionResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetLegislationForSession", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetLegislationForSession")
    @ResponseWrapper(localName = "GetLegislationForSessionResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetLegislationForSessionResponse")
    public ArrayOfLegislationIndex getLegislationForSession(
        @WebParam(name = "SessionId", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer sessionId);

    /**
     * 
     * @param documentType
     * @param sessionId
     * @param rangeSize
     * @return
     *     returns gov.ga.legis.legislation.ArrayOfLegislationIndexRangeSet
     */
    @WebMethod(operationName = "GetLegislationRanges", action = "http://www.legis.ga.gov/2009/01/01/services/LegislationSearch/GetLegislationRanges")
    @WebResult(name = "GetLegislationRangesResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetLegislationRanges", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetLegislationRanges")
    @ResponseWrapper(localName = "GetLegislationRangesResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetLegislationRangesResponse")
    public ArrayOfLegislationIndexRangeSet getLegislationRanges(
        @WebParam(name = "SessionId", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer sessionId,
        @WebParam(name = "DocumentType", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        DocumentType documentType,
        @WebParam(name = "RangeSize", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer rangeSize);

    /**
     * 
     * @param range
     * @return
     *     returns gov.ga.legis.legislation.LegislationIndexRange
     */
    @WebMethod(operationName = "GetLegislationRange", action = "http://www.legis.ga.gov/2009/01/01/services/LegislationSearch/GetLegislationRange")
    @WebResult(name = "GetLegislationRangeResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetLegislationRange", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetLegislationRange")
    @ResponseWrapper(localName = "GetLegislationRangeResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetLegislationRangeResponse")
    public LegislationIndexRange getLegislationRange(
        @WebParam(name = "Range", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        LegislationIndexRangeSet range);

    /**
     * 
     * @param legislationId
     * @return
     *     returns gov.ga.legis.legislation.LegislationDetail
     */
    @WebMethod(operationName = "GetLegislationDetail", action = "http://www.legis.ga.gov/2009/01/01/services/LegislationSearch/GetLegislationDetail")
    @WebResult(name = "GetLegislationDetailResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetLegislationDetail", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetLegislationDetail")
    @ResponseWrapper(localName = "GetLegislationDetailResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetLegislationDetailResponse")
    public LegislationDetail getLegislationDetail(
        @WebParam(name = "LegislationId", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer legislationId);

    /**
     * 
     * @param number
     * @param documentType
     * @param sessionId
     * @return
     *     returns gov.ga.legis.legislation.LegislationDetail
     */
    @WebMethod(operationName = "GetLegislationDetailByDescription", action = "http://www.legis.ga.gov/2009/01/01/services/LegislationSearch/GetLegislationDetailByDescription")
    @WebResult(name = "GetLegislationDetailByDescriptionResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetLegislationDetailByDescription", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetLegislationDetailByDescription")
    @ResponseWrapper(localName = "GetLegislationDetailByDescriptionResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetLegislationDetailByDescriptionResponse")
    public LegislationDetail getLegislationDetailByDescription(
        @WebParam(name = "DocumentType", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        DocumentType documentType,
        @WebParam(name = "Number", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer number,
        @WebParam(name = "SessionId", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer sessionId);

    /**
     * 
     * @return
     *     returns gov.ga.legis.legislation.ArrayOfSubject
     */
    @WebMethod(operationName = "GetTitles", action = "http://www.legis.ga.gov/2009/01/01/services/LegislationSearch/GetTitles")
    @WebResult(name = "GetTitlesResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetTitles", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetTitles")
    @ResponseWrapper(localName = "GetTitlesResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.legislation.GetTitlesResponse")
    public ArrayOfSubject getTitles();

}
