
package gov.ga.legis.legislation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LegislationService", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", wsdlLocation = "http://webservices.legis.ga.gov/GGAServices/Legislation/Service.svc?wsdl")
public class LegislationService
    extends Service
{

    private final static URL LEGISLATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException LEGISLATIONSERVICE_EXCEPTION;
    private final static QName LEGISLATIONSERVICE_QNAME = new QName("http://www.legis.ga.gov/2009/01/01/services/", "LegislationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservices.legis.ga.gov/GGAServices/Legislation/Service.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LEGISLATIONSERVICE_WSDL_LOCATION = url;
        LEGISLATIONSERVICE_EXCEPTION = e;
    }

    public LegislationService() {
        super(__getWsdlLocation(), LEGISLATIONSERVICE_QNAME);
    }

    public LegislationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LEGISLATIONSERVICE_QNAME, features);
    }

    public LegislationService(URL wsdlLocation) {
        super(wsdlLocation, LEGISLATIONSERVICE_QNAME);
    }

    public LegislationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LEGISLATIONSERVICE_QNAME, features);
    }

    public LegislationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LegislationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LegislationSearch
     */
    @WebEndpoint(name = "BasicHttpBinding_LegislationSearch")
    public LegislationSearch getBasicHttpBindingLegislationSearch() {
        return super.getPort(new QName("http://www.legis.ga.gov/2009/01/01/services/", "BasicHttpBinding_LegislationSearch"), LegislationSearch.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LegislationSearch
     */
    @WebEndpoint(name = "BasicHttpBinding_LegislationSearch")
    public LegislationSearch getBasicHttpBindingLegislationSearch(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.legis.ga.gov/2009/01/01/services/", "BasicHttpBinding_LegislationSearch"), LegislationSearch.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LEGISLATIONSERVICE_EXCEPTION!= null) {
            throw LEGISLATIONSERVICE_EXCEPTION;
        }
        return LEGISLATIONSERVICE_WSDL_LOCATION;
    }

}
