
package gov.ga.legis.votes;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RollCallNotPublishedFault", targetNamespace = "http://www.legis.ga.gov/2009/01/01/data/")
public class VoteFinderGetVoteRollCallNotPublishedFaultFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RollCallNotPublishedFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public VoteFinderGetVoteRollCallNotPublishedFaultFaultFaultMessage(String message, RollCallNotPublishedFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public VoteFinderGetVoteRollCallNotPublishedFaultFaultFaultMessage(String message, RollCallNotPublishedFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: gov.ga.legis.votes.RollCallNotPublishedFault
     */
    public RollCallNotPublishedFault getFaultInfo() {
        return faultInfo;
    }

}
