
package gov.ga.legis.votes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VoteService", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", wsdlLocation = "http://webservices.legis.ga.gov/GGAServices/Votes/Service.svc?wsdl")
public class VoteService
    extends Service
{

    private final static URL VOTESERVICE_WSDL_LOCATION;
    private final static WebServiceException VOTESERVICE_EXCEPTION;
    private final static QName VOTESERVICE_QNAME = new QName("http://www.legis.ga.gov/2009/01/01/services/", "VoteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservices.legis.ga.gov/GGAServices/Votes/Service.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VOTESERVICE_WSDL_LOCATION = url;
        VOTESERVICE_EXCEPTION = e;
    }

    public VoteService() {
        super(__getWsdlLocation(), VOTESERVICE_QNAME);
    }

    public VoteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VOTESERVICE_QNAME, features);
    }

    public VoteService(URL wsdlLocation) {
        super(wsdlLocation, VOTESERVICE_QNAME);
    }

    public VoteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VOTESERVICE_QNAME, features);
    }

    public VoteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VoteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VoteFinder
     */
    @WebEndpoint(name = "BasicHttpBinding_VoteFinder")
    public VoteFinder getBasicHttpBindingVoteFinder() {
        return super.getPort(new QName("http://www.legis.ga.gov/2009/01/01/services/", "BasicHttpBinding_VoteFinder"), VoteFinder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VoteFinder
     */
    @WebEndpoint(name = "BasicHttpBinding_VoteFinder")
    public VoteFinder getBasicHttpBindingVoteFinder(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.legis.ga.gov/2009/01/01/services/", "BasicHttpBinding_VoteFinder"), VoteFinder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VOTESERVICE_EXCEPTION!= null) {
            throw VOTESERVICE_EXCEPTION;
        }
        return VOTESERVICE_WSDL_LOCATION;
    }

}
