
package gov.ga.legis.session;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SessionService", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", wsdlLocation = "http://webservices.legis.ga.gov/GGAServices/Session/Service.svc?wsdl")
public class SessionService
    extends Service
{

    private final static URL SESSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException SESSIONSERVICE_EXCEPTION;
    private final static QName SESSIONSERVICE_QNAME = new QName("http://www.legis.ga.gov/2009/01/01/services/", "SessionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservices.legis.ga.gov/GGAServices/Session/Service.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SESSIONSERVICE_WSDL_LOCATION = url;
        SESSIONSERVICE_EXCEPTION = e;
    }

    public SessionService() {
        super(__getWsdlLocation(), SESSIONSERVICE_QNAME);
    }

    public SessionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SESSIONSERVICE_QNAME, features);
    }

    public SessionService(URL wsdlLocation) {
        super(wsdlLocation, SESSIONSERVICE_QNAME);
    }

    public SessionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SESSIONSERVICE_QNAME, features);
    }

    public SessionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SessionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SessionFinder
     */
    @WebEndpoint(name = "BasicHttpBinding_SessionFinder")
    public SessionFinder getBasicHttpBindingSessionFinder() {
        return super.getPort(new QName("http://www.legis.ga.gov/2009/01/01/services/", "BasicHttpBinding_SessionFinder"), SessionFinder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SessionFinder
     */
    @WebEndpoint(name = "BasicHttpBinding_SessionFinder")
    public SessionFinder getBasicHttpBindingSessionFinder(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.legis.ga.gov/2009/01/01/services/", "BasicHttpBinding_SessionFinder"), SessionFinder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SESSIONSERVICE_EXCEPTION!= null) {
            throw SESSIONSERVICE_EXCEPTION;
        }
        return SESSIONSERVICE_WSDL_LOCATION;
    }

}
