
package gov.ga.legis.committees;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CommitteeService", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", wsdlLocation = "http://webservices.legis.ga.gov/GGAServices/Committees/Service.svc?wsdl")
public class CommitteeService
    extends Service
{

    private final static URL COMMITTEESERVICE_WSDL_LOCATION;
    private final static WebServiceException COMMITTEESERVICE_EXCEPTION;
    private final static QName COMMITTEESERVICE_QNAME = new QName("http://www.legis.ga.gov/2009/01/01/services/", "CommitteeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservices.legis.ga.gov/GGAServices/Committees/Service.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMITTEESERVICE_WSDL_LOCATION = url;
        COMMITTEESERVICE_EXCEPTION = e;
    }

    public CommitteeService() {
        super(__getWsdlLocation(), COMMITTEESERVICE_QNAME);
    }

    public CommitteeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMITTEESERVICE_QNAME, features);
    }

    public CommitteeService(URL wsdlLocation) {
        super(wsdlLocation, COMMITTEESERVICE_QNAME);
    }

    public CommitteeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMITTEESERVICE_QNAME, features);
    }

    public CommitteeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommitteeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommitteeFinder
     */
    @WebEndpoint(name = "BasicHttpBinding_CommitteeFinder")
    public CommitteeFinder getBasicHttpBindingCommitteeFinder() {
        return super.getPort(new QName("http://www.legis.ga.gov/2009/01/01/services/", "BasicHttpBinding_CommitteeFinder"), CommitteeFinder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommitteeFinder
     */
    @WebEndpoint(name = "BasicHttpBinding_CommitteeFinder")
    public CommitteeFinder getBasicHttpBindingCommitteeFinder(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.legis.ga.gov/2009/01/01/services/", "BasicHttpBinding_CommitteeFinder"), CommitteeFinder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMITTEESERVICE_EXCEPTION!= null) {
            throw COMMITTEESERVICE_EXCEPTION;
        }
        return COMMITTEESERVICE_WSDL_LOCATION;
    }

}
