
package gov.ga.legis.committees;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommitteeFinder", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommitteeFinder {


    /**
     * 
     * @param sessionId
     * @return
     *     returns gov.ga.legis.committees.ArrayOfCommitteeListing
     */
    @WebMethod(operationName = "GetCommitteesBySession", action = "http://www.legis.ga.gov/2009/01/01/services/CommitteeFinder/GetCommitteesBySession")
    @WebResult(name = "GetCommitteesBySessionResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetCommitteesBySession", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.committees.GetCommitteesBySession")
    @ResponseWrapper(localName = "GetCommitteesBySessionResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.committees.GetCommitteesBySessionResponse")
    public ArrayOfCommitteeListing getCommitteesBySession(
        @WebParam(name = "SessionId", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer sessionId);

    /**
     * 
     * @param sessionId
     * @param type
     * @return
     *     returns gov.ga.legis.committees.ArrayOfCommitteeListing
     */
    @WebMethod(operationName = "GetCommitteesByTypeAndSession", action = "http://www.legis.ga.gov/2009/01/01/services/CommitteeFinder/GetCommitteesByTypeAndSession")
    @WebResult(name = "GetCommitteesByTypeAndSessionResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetCommitteesByTypeAndSession", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.committees.GetCommitteesByTypeAndSession")
    @ResponseWrapper(localName = "GetCommitteesByTypeAndSessionResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.committees.GetCommitteesByTypeAndSessionResponse")
    public ArrayOfCommitteeListing getCommitteesByTypeAndSession(
        @WebParam(name = "Type", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        CommitteeType type,
        @WebParam(name = "SessionId", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer sessionId);

    /**
     * 
     * @param committeeId
     * @return
     *     returns gov.ga.legis.committees.CommitteeDetail
     */
    @WebMethod(operationName = "GetCommittee", action = "http://www.legis.ga.gov/2009/01/01/services/CommitteeFinder/GetCommittee")
    @WebResult(name = "GetCommitteeResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetCommittee", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.committees.GetCommittee")
    @ResponseWrapper(localName = "GetCommitteeResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.committees.GetCommitteeResponse")
    public CommitteeDetail getCommittee(
        @WebParam(name = "CommitteeId", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer committeeId);

    /**
     * 
     * @param committeeId
     * @param sessionId
     * @return
     *     returns gov.ga.legis.committees.CommitteeDetail
     */
    @WebMethod(operationName = "GetCommitteeForSession", action = "http://www.legis.ga.gov/2009/01/01/services/CommitteeFinder/GetCommitteeForSession")
    @WebResult(name = "GetCommitteeForSessionResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetCommitteeForSession", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.committees.GetCommitteeForSession")
    @ResponseWrapper(localName = "GetCommitteeForSessionResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.committees.GetCommitteeForSessionResponse")
    public CommitteeDetail getCommitteeForSession(
        @WebParam(name = "CommitteeId", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer committeeId,
        @WebParam(name = "SessionId", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer sessionId);

}
