
package gov.ga.legis.members;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MemberService", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", wsdlLocation = "http://webservices.legis.ga.gov/GGAServices/Members/Service.svc?wsdl")
public class MemberService
    extends Service
{

    private final static URL MEMBERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MEMBERSERVICE_EXCEPTION;
    private final static QName MEMBERSERVICE_QNAME = new QName("http://www.legis.ga.gov/2009/01/01/services/", "MemberService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservices.legis.ga.gov/GGAServices/Members/Service.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEMBERSERVICE_WSDL_LOCATION = url;
        MEMBERSERVICE_EXCEPTION = e;
    }

    public MemberService() {
        super(__getWsdlLocation(), MEMBERSERVICE_QNAME);
    }

    public MemberService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEMBERSERVICE_QNAME, features);
    }

    public MemberService(URL wsdlLocation) {
        super(wsdlLocation, MEMBERSERVICE_QNAME);
    }

    public MemberService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEMBERSERVICE_QNAME, features);
    }

    public MemberService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MemberService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MemberFinder
     */
    @WebEndpoint(name = "BasicHttpBinding_MemberFinder")
    public MemberFinder getBasicHttpBindingMemberFinder() {
        return super.getPort(new QName("http://www.legis.ga.gov/2009/01/01/services/", "BasicHttpBinding_MemberFinder"), MemberFinder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MemberFinder
     */
    @WebEndpoint(name = "BasicHttpBinding_MemberFinder")
    public MemberFinder getBasicHttpBindingMemberFinder(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.legis.ga.gov/2009/01/01/services/", "BasicHttpBinding_MemberFinder"), MemberFinder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEMBERSERVICE_EXCEPTION!= null) {
            throw MEMBERSERVICE_EXCEPTION;
        }
        return MEMBERSERVICE_WSDL_LOCATION;
    }

}
