
package gov.ga.legis.members;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MemberFinder", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MemberFinder {


    /**
     * 
     * @param sessionId
     * @return
     *     returns gov.ga.legis.members.ArrayOfMemberListing
     */
    @WebMethod(operationName = "GetMembersBySession", action = "http://www.legis.ga.gov/2009/01/01/services/MemberFinder/GetMembersBySession")
    @WebResult(name = "GetMembersBySessionResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetMembersBySession", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.members.GetMembersBySession")
    @ResponseWrapper(localName = "GetMembersBySessionResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.members.GetMembersBySessionResponse")
    public ArrayOfMemberListing getMembersBySession(
        @WebParam(name = "SessionId", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer sessionId);

    /**
     * 
     * @param sessionId
     * @param type
     * @return
     *     returns gov.ga.legis.members.ArrayOfMemberListing
     */
    @WebMethod(operationName = "GetMembersByTypeAndSession", action = "http://www.legis.ga.gov/2009/01/01/services/MemberFinder/GetMembersByTypeAndSession")
    @WebResult(name = "GetMembersByTypeAndSessionResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetMembersByTypeAndSession", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.members.GetMembersByTypeAndSession")
    @ResponseWrapper(localName = "GetMembersByTypeAndSessionResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.members.GetMembersByTypeAndSessionResponse")
    public ArrayOfMemberListing getMembersByTypeAndSession(
        @WebParam(name = "Type", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        MemberType type,
        @WebParam(name = "SessionId", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer sessionId);

    /**
     * 
     * @param memberId
     * @return
     *     returns gov.ga.legis.members.Member
     */
    @WebMethod(operationName = "GetMember", action = "http://www.legis.ga.gov/2009/01/01/services/MemberFinder/GetMember")
    @WebResult(name = "GetMemberResult", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
    @RequestWrapper(localName = "GetMember", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.members.GetMember")
    @ResponseWrapper(localName = "GetMemberResponse", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/", className = "gov.ga.legis.members.GetMemberResponse")
    public Member getMember(
        @WebParam(name = "MemberId", targetNamespace = "http://www.legis.ga.gov/2009/01/01/services/")
        Integer memberId);

}
